-- MySQL Script generated by MySQL Workbench
-- Thu Dec 12 21:22:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nature
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nature
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nature` DEFAULT CHARACTER SET utf8 ;
USE `nature` ;

-- -----------------------------------------------------
-- Table `nature`.`admin_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nature`.`admin_user` (
  `UID` VARCHAR(12) NOT NULL COMMENT '\'管理员id\'',
  `UNAME` VARCHAR(45) NULL COMMENT '\'管理员名称\'',
  `USEX` INT(2) NULL COMMENT '性别',
  `UPIC` VARCHAR(40) NULL COMMENT '\'头像地址\'',
  `UACCOUNT` VARCHAR(12) NULL COMMENT '\'管理员账号，登陆凭证\'',
  `UPASSWORD` VARCHAR(20) NULL COMMENT '\'登陆密码\'',
  `UPERM` INT(2) NULL COMMENT '管理员权限 1-最高权限 2-稍次一点权限',
  `UMSG` VARCHAR(20) NULL COMMENT '\'管理员当前待处理信息\'',
  `UEMAIL` VARCHAR(20) NULL COMMENT '\'管理员电子邮箱\'',
  `UTEL` VARCHAR(11) NULL,
  PRIMARY KEY (`UID`),
  UNIQUE INDEX `UID_UNIQUE` (`UID` ASC) VISIBLE,
  UNIQUE INDEX `UACCOUNT_UNIQUE` (`UACCOUNT` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
